name: capfiscal_app
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_functions: ^4.6.0
  flutter_stripe: ^10.1.1
  mobile_scanner: ^5.0.1
  qr_flutter: ^4.1.0
  intl: ^0.18.1

flutter:
  uses-material-design: true
